# Generated by Django 5.2.15 on 2026-06-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('email', 'Email'), ('call', 'Phone Call'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.IntegerField(default=0, help_text='Probability percentage'),
        ),
    ]
