import os

PROJECTS_ROOT = r"D:\Coding_Projects\100 Django Projects"
OUTPUT_README = os.path.join(PROJECTS_ROOT, "README.md")

IGNORE_FOLDERS = {".git", ".vscode", ".idea", "__pycache__"}
VENV_NAMES = {"venv", "ss_venv", "env"}

projects = []

for name in sorted(os.listdir(PROJECTS_ROOT)):
    path = os.path.join(PROJECTS_ROOT, name)

    if not os.path.isdir(path):
        continue
    if name in IGNORE_FOLDERS:
        continue

    description = "No description yet"
    status = "Planned"
    ready = "❌"

    # description.txt
    desc_path = os.path.join(path, "description.txt")
    if os.path.exists(desc_path):
        with open(desc_path, "r", encoding="utf-8") as f:
            description = f.read().strip()

    # manage.py detection
    if any(f.lower() == "manage.py" for f in os.listdir(path)):
        status = "Completed"

    # venv detection
    if any(os.path.isdir(os.path.join(path, v)) for v in VENV_NAMES):
        ready = "✅"

    projects.append((name, description, status, ready))

# overwrite README completely
with open(OUTPUT_README, "w", encoding="utf-8") as f:
    f.write("# 100 Django Projects Portfolio\n\n")
    f.write("> A curated collection of Django projects demonstrating Django mastery through real-world applications.\n\n")
    
    f.write("**Progress:** {} / 100 completed\n\n".format(len([p for p in projects if p[3] == "✅"])))
    
    f.write("---\n\n")
    f.write("## 📌 Project Index\n\n")
    f.write("| # | Project Name | Description | Status | Ready to Run |\n")
    f.write("|---|--------------|-------------|--------|--------------|\n")

    for i, (name, desc, status, ready) in enumerate(projects, start=1):
        f.write(f"| {i} | [{name}]({name.replace(' ', '%20')}) | {desc} | {status} | {ready} |\n")

    f.write("\n---\n\n")
    f.write("## ⚙️ How to Run a Project\n\n")
    f.write("1. Navigate to the project folder\n")
    f.write("2. Install dependencies:\n")
    f.write("   ```bash\n")
    f.write("   pip install -r requirements.txt\n")
    f.write("   ```\n")
    f.write("3. Apply migrations:\n")
    f.write("   ```bash\n")
    f.write("   python manage.py makemigrations\n")
    f.write("   python manage.py migrate\n")
    f.write("   ```\n")
    f.write("4. Run the development server:\n")
    f.write("   ```bash\n")
    f.write("   python manage.py runserver\n")
    f.write("   ```\n")
    f.write("5. Open your browser:\n")
    f.write("   ```\n")
    f.write("   http://127.0.0.1:8000/\n")
    f.write("   ```\n\n")
    f.write("---\n\n")
    f.write("## 📌 Notes\n\n")
    f.write("- Projects are numbered to track long-term progress\n")
    f.write("- ✅ Ready to Run = manage.py + requirements.txt present\n")
    f.write("- ❌ Not Ready = setup still required\n")
    f.write("- This README is auto-generated\n")
    f.write("- Do NOT edit this file manually\n\n")
    f.write("---\n\n")
    f.write("## ⚖️ License\n\n")
    f.write("MIT License.\n")

print("✅ Clean README.md generated successfully")