# Generated by Django 5.2.10 on 2026-02-02 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-enrollment_date', 'last_name']},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='core_studen_student_fa4380_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='core_studen_email_26bdb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='core_studen_status_c9d890_idx',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='result',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='result',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='result',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('', 'Not Graded')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='result',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
    ]
