# Generated by Django 5.2.9 on 2025-12-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
