# Generated by Django 5.2.14 on 2026-05-14 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500, unique=True)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('format', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(choices=[('original', 'Original'), ('thumbnail', 'Thumbnail'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=500, unique=True)),
                ('file_size', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_versions', to='images.image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
