# Generated by Django 5.2.12 on 2026-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Optional: Use an image URL instead of uploading', null=True),
        ),
    ]
